const mockData = [
    { id: 1, name: "Java" },
    { id: 2, name: "React" },
    { id: 3, name: "JavaScript" },
    { id: 4, name: "Python" },
    { id: 5, name: "HTML" },
    { id: 6, name: "CSS" },
    { id: 7, name: "C++" },
    { id: 8, name: "C#" },
    { id: 9, name: "PHP" },
    { id: 10, name: "SQL" },
    { id: 11, name: "Ruby" },
    { id: 12, name: "Swift" },
    { id: 13, name: "Objective-C" },
    { id: 14, name: "R" },
    { id: 15, name: "Go" },
    { id: 16, name: "TypeScript" },
    { id: 17, name: "Angular" },
    { id: 18, name: "Vue.js" },
    { id: 19, name: "Node.js" },
    { id: 20, name: "Express.js" },
    { id: 21, name: "MongoDB" },
    { id: 22, name: "Firebase" },
    { id: 23, name: "Django" },
    { id: 24, name: "Flask" },
    { id: 25, name: "Ruby on Rails" },
    { id: 26, name: "Spring" },
    { id: 27, name: "ASP.NET" },
    { id: 28, name: "Laravel" },
    { id: 29, name: "Symfony" },
    { id: 30, name: "Redux" },
    { id: 31, name: "GraphQL" },
    { id: 32, name: "RESTful APIs" },
    { id: 33, name: "SOAP" },
    { id: 34, name: "Jenkins" },
    { id: 35, name: "Docker" },
    { id: 36, name: "Kubernetes" },
    { id: 37, name: "Git" },
    { id: 38, name: "Subversion (SVN)" },
    { id: 39, name: "Mercurial" },
    { id: 40, name: "Jira" },
    { id: 41, name: "Confluence" },
    { id: 42, name: "Trello" },
    { id: 43, name: "Bitbucket" },
    { id: 44, name: "Agile Methodologies" },
    { id: 45, name: "Scrum" },
    { id: 46, name: "Kanban" },
    { id: 47, name: "Lean Software Development" },
    { id: 48, name: "Continuous Integration (CI)" },
    { id: 49, name: "Continuous Deployment (CD)" },
    { id: 50, name: "Test-Driven Development (TDD)" },
   
];

export default mockData;